# -*- coding: utf-8 -*-
"""EstagioTargetSistemas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ue2O6fDbyZl_gmU12dsxQpYQYFQlNeMw

#Questão 1

1) Observe o trecho de código abaixo:

int INDICE = 13, SOMA = 0, K = 0;

enquanto K < INDICE faça

{

K = K + 1;

SOMA = SOMA + K;

}

imprimir(SOMA);



Ao final do processamento, qual será o valor da variável SOMA?
"""

indice = 13;
soma = 0;
k = 0;

while k < indice:
  k += 1;
  soma += k;

print("O valor da soma será:" , soma);

"""#Questão 2

2) Dado a sequência de Fibonacci, onde se inicia por 0 e 1 e o próximo valor sempre será a soma dos 2 valores anteriores (exemplo: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...), escreva um programa na linguagem que desejar onde, informado um número, ele calcule a sequência de Fibonacci e retorne uma mensagem avisando se o número informado pertence ou não a sequência.



IMPORTANTE:

Esse número pode ser informado através de qualquer entrada de sua preferência ou pode ser previamente definido no código;

"""

def fibonaccisequencia(numero):
  fibonacci = [0,1] #Cria uma lista com os dois primeiros números da sequencia fibonacci
  while fibonacci [-1] < numero: #Enquanto o último número da lista de fibonacci for menor que o número informado
    fibonacci.append(fibonacci[-1] + fibonacci[-2]) #Ele adiciona na lista fibonacci a soma do último elemento + o penultimo elemento
  return fibonacci

def verificaONumero(numero):
  fibonacci = fibonaccisequencia(numero) #Após a função fibonacci, nomeamos a função para fibonacci
  if numero in fibonacci: # Logo após verificamos se o numero informado pelo usuário está dentro da lista fibonacci gerada na outra função
    return True
  else:
    return False

numero = int(input("Informe um número inteiro: ")); #Solicita um número ao usuário

if verificaONumero(numero):
  print('O número', numero,'pertence a sequência Fibonacci');
else:
  print('O número', numero,'não pertence a sequência Fibonacci')

"""#Questão 3

3) Descubra a lógica e complete o próximo elemento:

a) 1, 3, 5, 7, ___

b) 2, 4, 8, 16, 32, 64, ____

c) 0, 1, 4, 9, 16, 25, 36, ____

d) 4, 16, 36, 64, ____

e) 1, 1, 2, 3, 5, 8, ____

f) 2,10, 12, 16, 17, 18, 19, ____

#Resposta

A) A lógica é somar 2 ao número anterior. Logo, a sequencia seria 1,3,5,7,9

B) A lógica é multiplicar 2 ao número anterior. Logo, a sequencia é 2,4,8,16,32,64,128

C) A lógica desse envolve o quadrado dos números começando em zero. Logo, a sequência é 0,1,4,9,16,25,36,49

D) A lógica desse é o quadrado dos número pares começando por 2. A sequência é 4,16,36,64,100

E) A lógica desse é semelhante a sequencia Fibonacci. Começa com 1 e soma-se com o número anterior para gerar o próximo número. Logo, a sequencia fica 1,1,2,3,5,8,13

F) Pela lógica, o próximo número seria o 20, já que não há uma sequencia clara, mas a partir do número 16, há um incremento de 1. Logo, a sequencia é 2,10,12,16,17,18,19,20

#Questão 4

4) Você está em uma sala com três interruptores, cada um conectado a uma lâmpada em uma sala diferente. Você não pode ver as lâmpadas da sala em que está, mas pode ligar e desligar os interruptores quantas vezes quiser. Seu objetivo é descobrir qual interruptor controla qual lâmpada.

Como você faria para descobrir, usando apenas duas idas até uma das salas das lâmpadas, qual interruptor controla cada lâmpada?

Resposta:

Primeiro, eu acenderia o primeiro interruptor e o deixaria por um tempo aceso e o desligaria. Depois ligaria o segundo e o deixaria ativo.

Iria até a sala e verificaria qual luz está acesa. Além disso, iria conferir a temperatura das outras duas lampadas apagas. A que estivesse quente, significaria que está conectada com o primeiro interruptor, enquanto a que estivesse fria, por consequência, estaria fria e liga ao terceiro interruptor não ativado.

#Questão 5

5) Escreva um programa que inverta os caracteres de um string.
"""

palavra = "banana"[::-1];

print(palavra);